### ISSUE TITLE
🐞 - Maskito fails to load in lazy loaded component

### ISSUE THREAD

**Issue by Tjax33** [taiga-family/maskito#503]
### Which package(s) are the source of the bug?

@maskito/core, @maskito/kit, @maskito/angular

### Playground Link

https://stackblitz.com/edit/angular-vhmfsm

### Description

Maskito works fine with my NG Zorro datepicker in the root app.component.
When trying to use the exact same code in a lazy loaded component. I get the below error. Not sure what is missing here but the maskito library is being imported into the child component module.

I have created a stackblitz where the first datepicker is the appcomponent root. The second datepicker is the lazy loaded component

Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
at validateValueWithMask (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:221:22)
at calibrateValueByMask (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:297:11)
at new MaskModel (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:354:18)
at maskitoTransform (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:674:23)
at Maskito.ensureValueFitsMask (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:885:33)
at new Maskito (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/core@1.5.1/index.umd.js:705:15)
at eval (https://angular-vhmfsm.stackblitz.io/turbo_modules/@maskito/angular@1.5.1/bundles/maskito-angular.umd.js:563:55)
at _ZoneDelegate.invoke (https://angular-vhmfsm.stackblitz.io/turbo_modules/zone.js@0.13.2/bundles/zone.umd.js:411:30)
at Zone.run (https://angular-vhmfsm.stackblitz.io/turbo_modules/zone.js@0.13.2/bundles/zone.umd.js:165:47)
at NgZone.runOutsideAngular (https://angular-vhmfsm.stackblitz.io/turbo_modules/@angular/core@16.2.4/fesm2022/core.mjs:10911:28)

### Maskito version

1.5.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@Tjax33 Hello!

`nz-date-picker` in **lazy loaded component** has empty content during its the first ngOnChanges (I don't know why).
What is why Maskito cannot find any native `<input />`.

```html
<nz-date-picker
    nzplaceholder="MM/DD/YYYY"
    class="ng-tns-c802749266-1"
    ng-reflect-nz-place-holder="MM/DD/YYYY"
    ng-reflect-maskito="[object Object]"
    ng-reflect-nz-format="MM/dd/yyyy"
>
    <!--container-->
    <!--container-->
    <!--container-->
    <!--container-->
    <!--container-->
></nz-date-picker>
```

<img width="1643" alt="debugger" src="https://github.com/taiga-family/maskito/assets/35179038/96aeb1fe-230d-49f4-892b-e34406a602af">


___
The most simple workaround - is to make `[elementPredicate]` async.

For example:

```ts
import { Component } from '@angular/core';
import { MaskitoElementPredicateAsync, MaskitoOptions } from '@maskito/core';
import { maskitoDateOptionsGenerator } from '@maskito/kit';

@Component({
  selector: 'child-welcome',
  template: `
    <nz-date-picker
      nzPlaceHolder="MM/DD/YYYY"
      [maskito]="maskOptions"
      [maskitoElement]="elementPredicate"
      [nzFormat]="'MM/dd/yyyy'"
      [(ngModel)]="date"
    ></nz-date-picker>
  `,
})
export class WelcomeComponent {
  date = null;
  maskOptions: MaskitoOptions = maskitoDateOptionsGenerator({
    mode: 'mm/dd/yyyy',
    separator: '/',
  });

  readonly elementPredicate: MaskitoElementPredicateAsync = async (host) =>
    new Promise((resolve) =>
      // next macro task
      setTimeout(() => resolve(host.querySelector<HTMLInputElement>('input')!))
    );
}
```
